using System;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using NUnit.Framework;
using UnityEngine;
using UnityEditor;
public sealed class ReynardTests
{
 static KaitRun Run(){var r=new KaitRun(new KaitBalanceConfig{initialThreatTiles=0,playerInvincible=true,enableThreatPillars=false});r.SelectCharacter(KaitCharacter.Reynard,924);for(int y=1;y<6;y++)for(int x=1;x<6;x++)r.walls[x,y]=false;return r;}
 static void Fox(KaitRun r,int x=2,int y=2,int value=8){r.Reynard.mirrorFoxCell=new Vector2Int(x,y);r.threat[x,y]=value;r.Reynard.spellReady[x,y]=true;}
 static List<KaitMergeEvent> Slide(KaitRun r,KaitDirection d)=> (List<KaitMergeEvent>)typeof(KaitRun).GetMethod("MoveThreatReynard",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{d,new List<KaitThreatMotion>()});
 static KaitEnemy Enemy(KaitRun r,int id,int x,int y,int hp=10){var e=new KaitEnemy{id=id,pos=new Vector2Int(x,y),hp=hp,maxHp=hp,type=KaitEnemyType.Grunt,life=KaitEnemyLife.Active};r.enemies.Add(e);return e;}
 [Test]public void PoolsStayIndependent(){Assert.AreEqual(24,ReynardCatalog.Pool().Count);Assert.AreEqual(12,ReynardCatalog.Cards.Count(d=>d.kind==KaitAbilityKind.Active));Assert.AreEqual(24,KaitAbilityCatalog.DefaultPool().Count);Assert.AreEqual(56,YummnCatalog.Pool().Count);Assert.AreEqual(24,ReynardCatalog.Cards.Select(d=>d.id).Distinct().Count());}
 [TestCase(2,1)][TestCase(4,2)][TestCase(8,3)][TestCase(16,4)][TestCase(32,5)]public void Levels(int v,int n){Assert.AreEqual(n,ReynardCatalog.Level(v));}
 [Test]public void SuccessfulMoveFiresOneDamageForward(){var r=Run();var e=Enemy(r,1,5,3);r.TryTurn(KaitDirection.Right);Assert.AreEqual(9,e.hp);Assert.AreEqual(1,r.Reynard.directionSpells);Assert.AreEqual(1,r.Reynard.enemyPhases);Assert.AreEqual(new Vector2Int(4,3),r.katePos);}
 [Test]public void BlockedMoveStillFiresInInputDirection(){var r=Run();var blocker=Enemy(r,1,4,3);var far=Enemy(r,2,5,3);r.TryTurn(KaitDirection.Right);Assert.AreEqual(9,blocker.hp);Assert.AreEqual(10,far.hp);Assert.AreEqual(1,r.Reynard.directionSpells);Assert.AreEqual(new Vector2Int(3,3),r.katePos);}
 [Test]public void PillarBlockedInputStillTriggersAttachedShotEffects(){var r=Run();r.walls[4,3]=true;r.Reynard.focusedSkill=KaitSkill.ReynardMissileArray;var target=Enemy(r,1,1,1);r.TryTurn(KaitDirection.Right);Assert.AreEqual(9,target.hp);Assert.AreEqual(1,r.Reynard.directionSpells);Assert.AreEqual(new Vector2Int(3,3),r.katePos);}
 [Test]public void BoundaryBlockedInputStillCreatesDirectionalProjectile(){var r=Run();typeof(KaitRun).GetProperty("katePos").SetValue(r,new Vector2Int(1,1));var result=r.TryTurn(KaitDirection.Left);var shot=result.reynardEvents.Find(e=>e.kind=="Bullet");Assert.NotNull(shot);Assert.AreEqual(new Vector2Int(1,1),shot.from);Assert.AreEqual(new Vector2Int(0,1),shot.to);Assert.AreEqual(new Vector2Int(1,1),r.katePos);}
 [Test]public void PiercingBulletHitsEveryEnemyInLine(){var r=Run();typeof(KaitRun).GetProperty("katePos").SetValue(r,new Vector2Int(1,3));var a=Enemy(r,1,3,3);var b=Enemy(r,2,5,3);r.passives.Add(KaitPassive.ReynardInterwoven);r.TryTurn(KaitDirection.Right);Assert.AreEqual(9,a.hp);Assert.AreEqual(9,b.hp);}
 [TestCase(KaitDirection.Left)][TestCase(KaitDirection.Right)][TestCase(KaitDirection.Up)][TestCase(KaitDirection.Down)]public void FoxNeverSlides(KaitDirection d){var r=Run();Fox(r);r.threat[0,0]=2;Slide(r,d);Assert.AreEqual(new Vector2Int(2,2),r.Reynard.mirrorFoxCell);Assert.AreEqual(8,r.threat[2,2]);}
 [Test]public void FoxOnlyMergesOnceFromBehind(){var r=Run();Fox(r,value:2);r.threat[3,2]=2;r.threat[4,2]=4;var m=Slide(r,KaitDirection.Left);Assert.AreEqual(4,r.threat[2,2]);Assert.AreEqual(4,r.threat[3,2]);Assert.AreEqual(1,m.Count);}
 [Test]public void ForwardTileCannotMergeBackwardsIntoFox(){var r=Run();Fox(r,value:2);r.threat[1,2]=2;Slide(r,KaitDirection.Left);Assert.AreEqual(2,r.threat[0,2]);Assert.AreEqual(2,r.threat[2,2]);}
 [Test]public void ExhaustionTravelsWithToken(){var r=Run();Fox(r);r.threat[4,0]=4;r.Reynard.spellReady[4,0]=false;Slide(r,KaitDirection.Left);Assert.AreEqual(4,r.threat[0,0]);Assert.False(r.Reynard.spellReady[0,0]);}
 [Test]public void WaitingDoesNotRefreshExhaustedNode(){var r=Run();Fox(r);r.Reynard.spellReady[2,2]=false;r.TryYummnWait();Assert.False(r.ReynardSlotReady);Assert.False(r.Reynard.hasLastDirection);}
 [Test]public void FailedSummonKeepsOldFox(){var r=Run();Fox(r,0,0);r.TryYummnWait();Assert.AreEqual(Vector2Int.zero,r.Reynard.mirrorFoxCell);}
 [Test]public void CastSpendsSlotNotNumberOrDirection(){var r=Run();Fox(r);r.skills.Add(KaitSkill.ReynardThunderwave);Assert.True(r.TryUseSkillAt(KaitSkill.ReynardThunderwave,r.katePos,out _));Assert.AreEqual(8,r.ReynardSlotValue);Assert.False(r.ReynardSlotReady);Assert.False(r.Reynard.hasLastDirection);Assert.AreEqual(1,r.Reynard.enemyPhases);}
 [Test]public void InvalidTargetDoesNotSpendOrAdvance(){var r=Run();Fox(r);r.skills.Add(KaitSkill.ReynardMistyStep);Assert.False(r.TryUseSkillAt(KaitSkill.ReynardMistyStep,new Vector2Int(0,0),out _));Assert.True(r.ReynardSlotReady);Assert.AreEqual(0,r.turn);}
 [Test]public void RepriseDoesNotRecurse(){var r=Run();Fox(r);r.skills.Add(KaitSkill.ReynardThunderwave);r.passives.Add(KaitPassive.ReynardReprise);var e=Enemy(r,1,4,3);r.TryUseSkillAt(KaitSkill.ReynardThunderwave,r.katePos,out _);Assert.AreEqual(6,e.hp);}
 [Test]public void SustainOnlyOneAndCannotRecastItself(){var r=Run();Fox(r);r.skills.Add(KaitSkill.ReynardMissileArray);r.skills.Add(KaitSkill.ReynardFoxfire);Assert.True(r.TryUseSkillAt(KaitSkill.ReynardMissileArray,r.katePos,out _));r.Reynard.spellReady[2,2]=true;Assert.False(r.TryUseSkillAt(KaitSkill.ReynardMissileArray,r.katePos,out _));Assert.True(r.TryUseSkillAt(KaitSkill.ReynardFoxfire,r.katePos,out _));Assert.AreEqual(KaitSkill.ReynardFoxfire,r.Reynard.focusedSkill);}
 [Test]public void DeadPrerequisitesNotDrawn(){var r=Run();Assert.False(r.EligibleAbilities().Exists(d=>d.passive==KaitPassive.ReynardReprise));r.skills.Add(KaitSkill.ReynardThunderwave);Assert.True(r.EligibleAbilities().Exists(d=>d.passive==KaitPassive.ReynardReprise));}
 [Test]public void ReplayRoundTrip(){var r=new KaitRun();r.SelectCharacter(KaitCharacter.Reynard,924);r.TryTurn(KaitDirection.Right);r.TryYummnWait();r.TryTurn(KaitDirection.Down);var other=new KaitRun();Assert.True(other.RestoreReplay(r.SaveReplay()));Assert.AreEqual(r.katePos,other.katePos);Assert.AreEqual(r.Reynard.mirrorFoxCell,other.Reynard.mirrorFoxCell);CollectionAssert.AreEqual(r.threat,other.threat);CollectionAssert.AreEqual(r.Reynard.spellReady,other.Reynard.spellReady);}
 [Test]public void SpineResourcesExist(){foreach(var id in new[]{"11202003","11300041","11300006","11201007","11202007","11300040","11101005"}){var a=Resources.Load<Spine.Unity.SkeletonDataAsset>("Characters/Reynard/"+id+"/"+id+"_SkeletonData");Assert.NotNull(a,id);Assert.NotNull(a.GetSkeletonData(false),id);}var player=Resources.Load<Spine.Unity.SkeletonDataAsset>("Characters/Reynard/11202003/11202003_SkeletonData").GetSkeletonData(false);Assert.NotNull(player.FindAnimation("walk"),"Reynard reuses Yummn exhausted-style walk movement");}
 [Test]public void EdenVoicesMatchReynardCast(){foreach(var cue in new[]{"Noel_Go_1","Noel_Battle_N_2","Noel_Battle_H_1","Noel_Battle_Hit_1","Noel_Battle_Die_1","Noel_Win_1","Noel_Fail_1"})Assert.NotNull(Resources.Load<AudioClip>("Audio/Voice/Reynard/Noel/"+cue),cue);var expected=new Dictionary<KaitEnemyType,string>{{KaitEnemyType.Grunt,"Chocolat"},{KaitEnemyType.Swordsman,"Stick"},{KaitEnemyType.Archer,"Quinn"},{KaitEnemyType.Guard,"Kiki"},{KaitEnemyType.Warlock,"Megumin"},{KaitEnemyType.ShieldKnight,"Nouet"}};foreach(var pair in expected){Assert.AreEqual(pair.Value,GameAudio.ReynardEnemyVoiceCharacter(pair.Key));string root="Audio/Voice/Reynard/Enemies/"+pair.Value+"/"+pair.Value+"_";Assert.NotNull(Resources.Load<AudioClip>(root+"Go_1"),pair.Key+" spawn");Assert.NotNull(Resources.Load<AudioClip>(root+"Battle_N_1"),pair.Key+" attack");Assert.NotNull(Resources.Load<AudioClip>(root+"Battle_Hit_1"),pair.Key+" hurt");Assert.NotNull(Resources.Load<AudioClip>(root+"Battle_Die_1"),pair.Key+" death");}}

 [Test]public void EveryCardHasTransparentArt(){foreach(var d in ReynardCatalog.Cards)Assert.NotNull(ReynardArt.Load("Cards/"+d.id.Substring(8)),d.id);}
 [Test]public void RuntimeEffectsNeverStartFromMissingWhiteImage(){for(int i=0;i<8;i++)Assert.NotNull(ReynardArt.ImpactFrame(i),"Impact frame "+i);var rift=Resources.Load<Sprite>("KaitVisuals/YummnRiftMask");Assert.NotNull(rift,"shared Yummn/Reynard alpha rift");var importer=AssetImporter.GetAtPath(AssetDatabase.GetAssetPath(rift.texture)) as TextureImporter;Assert.NotNull(importer);Assert.True(importer.DoesSourceTextureHaveAlpha(),"rift source must preserve alpha on every build target");}
 [Test]public void RecallRefreshesOnlyAdjacentRealMerge(){var r=Run();Fox(r);r.Reynard.spellReady[2,2]=false;r.passives.Add(KaitPassive.ReynardArcaneRecall);var result=new KaitTurnResult();typeof(KaitRun).GetMethod("RegisterReynardMerge",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{new KaitMergeEvent{resultValue=4,sourceValue=2,threatCell=new Vector2Int(2,3)},result});Assert.True(r.ReynardSlotReady);}
 [Test]public void DevourContinuesThroughSameValueNodes(){var r=Run();Fox(r,value:4);r.passives.Add(KaitPassive.ReynardArcaneDevour);r.threat[0,0]=4;r.threat[4,4]=8;var result=new KaitTurnResult();result.merges.Add(new KaitMergeEvent{resultValue=4,sourceValue=2,threatCell=new Vector2Int(2,2)});typeof(KaitRun).GetMethod("ProcessReynardMerges",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{result});Assert.AreEqual(16,r.ReynardSlotValue);Assert.AreEqual(3,result.merges.Count);}
 [Test]public void FogAtSourceStopsOwnRay(){var r=Run();Fox(r);r.Reynard.focusedSkill=KaitSkill.ReynardFog;r.Reynard.focusedCell=r.katePos;var e=Enemy(r,1,4,3);typeof(KaitRun).GetMethod("ReynardRay",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{Vector2Int.right,3,true,ReynardDamageKind.SpellDirect,new KaitTurnResult(),false});Assert.AreEqual(10,e.hp);}
 [Test]public void WebPreventsAutonomousMove(){var r=Run();var e=Enemy(r,1,1,3);r.Reynard.focusedSkill=KaitSkill.ReynardWeb;r.Reynard.focusedCell=e.pos;r.TryYummnWait();Assert.AreEqual(new Vector2Int(1,3),e.pos);}
 [Test]public void ChainLightningHitsAtMostFiveUniqueEnemies(){var r=Run();Fox(r,value:32);r.skills.Add(KaitSkill.ReynardChainLightning);for(int i=0;i<6;i++)Enemy(r,i,1+i%3,1+i/3);Assert.True(r.TryUseSkillAt(KaitSkill.ReynardChainLightning,new Vector2Int(2,2),out _));Assert.AreEqual(5,r.enemies.Count(e=>e.hp==7));}
 [Test]public void DirectionDamageNeverTriggersSpellDiffusion(){var r=Run();var a=Enemy(r,1,4,3);var b=Enemy(r,2,4,4);r.passives.Add(KaitPassive.ReynardDiffusion);typeof(KaitRun).GetMethod("ReynardRay",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{Vector2Int.right,1,true,ReynardDamageKind.DirectionSpell,new KaitTurnResult(),false});Assert.AreEqual(9,a.hp);Assert.AreEqual(10,b.hp);}
 [Test]public void OriginalEnemiesDoNotAcquireNewChaseBehavior(){var r=Run();var e=Enemy(r,1,1,3);r.TryYummnWait();Assert.AreEqual(new Vector2Int(1,3),e.pos);}
}
