using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEngine;

public sealed class ReynardTests
{
 static KaitRun Run(){var r=new KaitRun(new KaitBalanceConfig{initialThreatTiles=0,playerInvincible=true,enableThreatPillars=false});r.SelectCharacter(KaitCharacter.Reynard,924);for(int y=1;y<6;y++)for(int x=1;x<6;x++)r.walls[x,y]=false;return r;}
 static KaitEnemy Enemy(KaitRun r,int id,int x,int y,int hp=10){var e=new KaitEnemy{id=id,pos=new Vector2Int(x,y),hp=hp,maxHp=hp,type=KaitEnemyType.Grunt,life=KaitEnemyLife.Active};r.enemies.Add(e);return e;}
 [Test]public void CandidatePoolHas42CardsAndExpectedKinds(){Assert.AreEqual(42,ReynardCatalog.Pool().Count);Assert.AreEqual(14,ReynardCatalog.Cards.Count(d=>d.kind==KaitAbilityKind.Active));Assert.AreEqual(28,ReynardCatalog.Cards.Count(d=>d.kind==KaitAbilityKind.Passive));Assert.AreEqual(2,ReynardCatalog.Legacy.Count);Assert.AreEqual(42,ReynardCatalog.Cards.Select(d=>d.id).Distinct().Count());}
 [Test]public void VersionAndSaveAreIsolated(){Assert.AreEqual("Reynard.0.6-targeted-shot-animation",ReynardCatalog.RulesVersion);Assert.AreEqual("reynard-dual42-animation-20260921",ReynardCatalog.Version);Assert.AreEqual("Kait.Run.Reynard.0.6",KaitVersion.ReynardSaveKey);}
 [Test]public void EveryDamagingEnemyAttackTriggersImmediateBodyHurt(){var method=typeof(KaitGame).GetMethod("ShouldPlayBodyHurt",BindingFlags.Static|BindingFlags.NonPublic);Assert.NotNull(method);foreach(var type in new[]{KaitIntentType.Melee,KaitIntentType.LineShot,KaitIntentType.CrossBlast})Assert.True((bool)method.Invoke(null,new object[]{new KaitEnemyAction{type=type,hitKate=true,damage=1},false}),type.ToString());Assert.False((bool)method.Invoke(null,new object[]{new KaitEnemyAction{type=KaitIntentType.Move,hitKate=true,damage=1},false}));}
 [Test]public void ReynardEnemyVisualScalesMatchTheirBodies(){Assert.AreEqual(1.18f,ReynardArt.EnemyVisualScale(KaitEnemyType.Swordsman),.001f);Assert.AreEqual(1.16f,ReynardArt.EnemyVisualScale(KaitEnemyType.Archer),.001f);Assert.AreEqual(1.18f,ReynardArt.EnemyVisualScale(KaitEnemyType.Guard),.001f);}
 [Test]public void BlockedMoveStillFiresInInputDirection(){var r=Run();var blocker=Enemy(r,1,4,3);var far=Enemy(r,2,5,3);var result=r.TryTurn(KaitDirection.Right);Assert.AreEqual(9,blocker.hp);Assert.AreEqual(10,far.hp);Assert.AreEqual(new Vector2Int(3,3),r.katePos);Assert.True(result.reynardEvents.Exists(e=>e.kind=="Bullet"));}
 [Test]public void EmptyForwardLaneOnlyMovesAndDoesNotCountAShot(){var r=Run();var result=r.TryTurn(KaitDirection.Right);Assert.AreEqual(new Vector2Int(4,3),r.katePos);Assert.False(result.reynardEvents.Exists(e=>e.kind=="Bullet"));Assert.AreEqual(0,r.Reynard.directionSpells);}
 [Test]public void EmptyForwardLaneDoesNotTriggerShotAfterPassives(){var r=Run();r.passives.Add(KaitPassive.ReynardMissileArrayPassive);var offAxis=Enemy(r,7,1,1);var result=r.TryTurn(KaitDirection.Right);Assert.AreEqual(10,offAxis.hp);Assert.False(result.reynardEvents.Exists(e=>e.kind=="Bullet"));}
 [Test]public void SpellAnimationClassesAreStable(){Assert.AreEqual("skill",ReynardCatalog.CastAnimation(KaitSkill.ReynardThunderwave));Assert.AreEqual("uniqueskill",ReynardCatalog.CastAnimation(KaitSkill.ReynardCounterspell));Assert.AreEqual("uniqueskill",ReynardCatalog.CastAnimation(KaitSkill.ReynardFog));Assert.AreEqual("uniqueskill",ReynardCatalog.CastAnimation(KaitSkill.ReynardStoneWall));Assert.AreEqual("prepare",ReynardCatalog.CastAnimation(KaitSkill.ReynardMistyStep));Assert.AreEqual("prepare",ReynardCatalog.CastAnimation(KaitSkill.ReynardWeb));}
 [Test]public void RealMergeCreatesSigil(){var r=Run();var result=new KaitTurnResult();var merge=new KaitMergeEvent{sourceValue=2,resultValue=4,threatCell=new Vector2Int(2,2)};typeof(KaitRun).GetMethod("RegisterReynardMerge",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{merge,result});Assert.True(r.Reynard.sigils[2,2]);Assert.AreEqual(1,r.ReynardSigilCount);}
 [Test]public void FoxMergeAlsoBuildsTail(){var r=Run();var result=new KaitTurnResult();var merge=new KaitMergeEvent{sourceValue=2,resultValue=4,threatCell=new Vector2Int(2,2),reynardFoxParticipated=true};typeof(KaitRun).GetMethod("RegisterReynardMerge",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{merge,result});Assert.AreEqual(1,r.Reynard.tails);}
 [Test]public void NineTailsChangesCap(){var r=Run();Assert.AreEqual(3,r.ReynardTailCap);r.passives.Add(KaitPassive.ReynardNineTails);Assert.AreEqual(9,r.ReynardTailCap);}
 [Test]public void TailNovaRequiresTailsOnly(){var r=Run();r.skills.Add(KaitSkill.ReynardTailNova);r.Reynard.sigils[2,2]=r.Reynard.sigils[2,3]=true;Assert.AreEqual("需要2条狐尾",r.ReynardCastFailure(KaitSkill.ReynardTailNova));r.Reynard.tails=2;Assert.IsNull(r.ReynardCastFailure(KaitSkill.ReynardTailNova));}
 [Test]public void MultipleFieldsCanCoexist(){var r=Run();for(int y=0;y<5;y++)r.Reynard.sigils[1,y]=true;r.skills.AddRange(new[]{KaitSkill.ReynardFog,KaitSkill.ReynardWeb});Assert.True(r.TryUseSkillAt(KaitSkill.ReynardFog,new Vector2Int(2,2),out _));Assert.True(r.TryUseSkillAt(KaitSkill.ReynardWeb,new Vector2Int(4,4),out _));Assert.AreEqual(new Vector2Int(2,2),r.Reynard.fogCell);Assert.AreEqual(new Vector2Int(4,4),r.Reynard.webCell);}
 [Test]public void TailsAbsorbBeforeHealth(){var r=new KaitRun(new KaitBalanceConfig{initialThreatTiles=0,playerInvincible=false,enableThreatPillars=false});r.SelectCharacter(KaitCharacter.Reynard,924);r.Reynard.tails=2;var result=new KaitTurnResult();typeof(KaitRun).GetMethod("DamageKate",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(r,new object[]{2,result,null});Assert.AreEqual(0,r.Reynard.tails);Assert.AreEqual(r.KateMaxHp,r.kateHp);}
 [Test]public void NewCardArtIsAddressable(){foreach(var id in Enumerable.Range(25,20).Select(n=>$"R{n:00}"))Assert.NotNull(ReynardArt.Load("Cards/"+id),id);}
 [Test]public void ApprovedActionEffectsAreAddressable(){foreach(var id in new[]{"SplitOrb","StarChaser","TailOverflow"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void ApprovedPassiveEffectsAreAddressable(){foreach(var id in new[]{"ChargedOrb","RuneDetonation","CircleResonance"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void ApprovedResourceEffectsAreAddressable(){foreach(var id in new[]{"ArcaneManifest","FoxfireGuard","FoxflameRite"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void ApprovedConversionEffectsAreAddressable(){foreach(var id in new[]{"TailToSigil","SpiritFoxHunt","TailwindChant"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void ApprovedAdvancedSpellEffectsAreAddressable(){foreach(var id in new[]{"ScorchingRay","RuneStep","StoneWall"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void ApprovedAdvancedSpellEffectsEmitFromTheirRules(){
  var ray=Run();ray.skills.Add(KaitSkill.ReynardScorchingRay);ray.Reynard.sigils[0,0]=ray.Reynard.sigils[0,1]=true;Enemy(ray,120,5,3);Assert.True(ray.TryUseSkillAt(KaitSkill.ReynardScorchingRay,new Vector2Int(4,3),out _));Assert.True(ray.lastSkillResult.reynardEvents.Exists(e=>e.kind=="ScorchingRay"&&e.to==new Vector2Int(5,3)));
  var step=Run();step.skills.Add(KaitSkill.ReynardRuneStep);step.Reynard.sigils[1,1]=step.Reynard.sigils[0,0]=true;Assert.True(step.TryUseSkillAt(KaitSkill.ReynardRuneStep,new Vector2Int(2,2),out _));Assert.True(step.lastSkillResult.reynardEvents.Exists(e=>e.kind=="RuneStep"&&e.to==new Vector2Int(2,2)));
  var wall=Run();wall.skills.Add(KaitSkill.ReynardStoneWall);wall.Reynard.sigils[0,0]=wall.Reynard.sigils[0,1]=true;Assert.True(wall.TryUseSkillAt(KaitSkill.ReynardStoneWall,new Vector2Int(4,4),out _));Assert.True(wall.lastSkillResult.reynardEvents.Exists(e=>e.kind=="StoneWall"&&e.to==new Vector2Int(4,4)));
 }
 [Test]public void MirrorFoxMotionKeepsTheOriginalTokenIdentity(){var r=Run();for(int y=0;y<r.ThreatSize;y++)for(int x=0;x<r.ThreatSize;x++)r.threat[x,y]=0;r.threat[1,2]=4;r.Reynard.mirrorFoxCell=new Vector2Int(1,2);var result=r.TryTurn(KaitDirection.Right);var fox=result.threatMotions.Where(m=>m.mirrorFox).ToList();Assert.AreEqual(1,fox.Count);Assert.AreEqual(new Vector2Int(1,2),fox[0].from);Assert.AreEqual(r.Reynard.mirrorFoxCell,fox[0].to);}
 [Test]public void FinalApprovedSpellAndSigilEffectsAreAddressable(){foreach(var id in new[]{"TailNova","MassHold","SigilIdle"})for(int frame=0;frame<8;frame++)Assert.NotNull(ReynardArt.SequenceFrame(id,frame),$"{id}:{frame}");}
 [Test]public void FinalApprovedSpellEffectsEmitFromTheirRules(){
  var nova=Run();nova.skills.Add(KaitSkill.ReynardTailNova);nova.Reynard.tails=2;Assert.True(nova.TryUseSkillAt(KaitSkill.ReynardTailNova,nova.katePos,out _));Assert.True(nova.lastSkillResult.reynardEvents.Exists(e=>e.kind=="TailNova"&&e.to==nova.katePos));
  var hold=Run();hold.skills.Add(KaitSkill.ReynardMassHold);for(int y=0;y<4;y++)hold.Reynard.sigils[0,y]=true;Assert.True(hold.TryUseSkillAt(KaitSkill.ReynardMassHold,new Vector2Int(4,4),out _));Assert.True(hold.lastSkillResult.reynardEvents.Exists(e=>e.kind=="MassHold"&&e.to==new Vector2Int(4,4)));
 }
 [Test]public void ApprovedResourceEffectsEmitFromTheirRules(){
  var manifest=Run();manifest.passives.Add(KaitPassive.ReynardArcaneManifest);var marked=Enemy(manifest,90,2,2);var result=new KaitTurnResult();var merge=new KaitMergeEvent{sourceValue=2,resultValue=4,threatCell=new Vector2Int(1,1)};typeof(KaitRun).GetMethod("RegisterReynardMerge",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(manifest,new object[]{merge,result});Assert.AreEqual(9,marked.hp);Assert.True(result.reynardEvents.Exists(e=>e.kind=="ArcaneManifest"&&e.to==marked.pos));
  var guard=new KaitRun(new KaitBalanceConfig{initialThreatTiles=0,playerInvincible=false,enableThreatPillars=false});guard.SelectCharacter(KaitCharacter.Reynard,924);guard.passives.Add(KaitPassive.ReynardTailGuard);guard.Reynard.tails=1;var attacker=Enemy(guard,91,4,3);result=new KaitTurnResult();typeof(KaitRun).GetMethod("DamageKate",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(guard,new object[]{1,result,attacker});Assert.AreEqual(9,attacker.hp);Assert.True(result.reynardEvents.Exists(e=>e.kind=="FoxfireGuard"&&e.to==attacker.pos));
  var rite=Run();rite.skills.Add(KaitSkill.ReynardFog);rite.passives.Add(KaitPassive.ReynardFoxfireRite);rite.Reynard.tails=1;var adjacent=Enemy(rite,92,4,3);Assert.True(rite.TryUseSkillAt(KaitSkill.ReynardFog,new Vector2Int(2,2),out _));Assert.AreEqual(9,adjacent.hp);Assert.True(rite.lastSkillResult.reynardEvents.Exists(e=>e.kind=="FoxflameRite"&&e.to==adjacent.pos));
 }
 [Test]public void CartoonPortraitIsAddressable(){Assert.NotNull(Resources.Load<Texture2D>("KaitVisuals/ReynardPortrait"));}
 [Test]public void ReplayRoundTrip(){var r=Run();r.TryTurn(KaitDirection.Right);r.TryYummnWait();var other=new KaitRun();Assert.True(other.RestoreReplay(r.SaveReplay()));Assert.AreEqual(r.katePos,other.katePos);CollectionAssert.AreEqual(r.Reynard.sigils,other.Reynard.sigils);Assert.AreEqual(r.Reynard.tails,other.Reynard.tails);}
}
