using System;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine;

public class YummnV081ContractTests
{
    [Test] public void PresentationDoesNotShowKillSupplyBeforeCombat(){var r=R();E(r,2,3,1);E(r,3,3,1);r.passives.Add(KaitPassive.FireSnake);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(0,a.yummnThreatAfterMerge.Cast<int>().Sum());Assert.AreEqual(4,a.yummnThreatAfterSupply.Cast<int>().Sum());Assert.AreEqual(4,a.threatAfter.Cast<int>().Sum());}
    [Test] public void EmptyThreatIsStarvationNotLock(){var r=R();Assert.IsTrue(r.YummnSupplyStarved);Assert.IsFalse(r.IsYummnThreatLocked());r.TryGlobalInput(KaitDirection.Right);Assert.IsFalse(r.ended);}
    const BindingFlags Hidden=BindingFlags.Instance|BindingFlags.NonPublic;
    static void Set(KaitRun r,string name,object value){var p=typeof(KaitRun).GetProperty(name);if(p!=null)p.SetValue(r,value);else typeof(KaitRun).GetField(name,Hidden).SetValue(r,value);}
    static object Call(KaitRun r,string name,params object[] args)=>typeof(KaitRun).GetMethod(name,Hidden).Invoke(r,args);
    static KaitRun R(bool alternative=false,bool eight=false,int x=1,int y=3)
{var r=new KaitRun();r.SelectCharacter(KaitCharacter.Yummn,801,new YummnRulesSnapshot(alternative?YummnTileSupplyMode.SkipStationaryPunch:YummnTileSupplyMode.KillOnly,eight,false,fiveKi:false,bossLine:false,actualMoveSupply:false));r.enemies.Clear();r.spawns.Clear();Array.Clear(r.threat,0,r.threat.Length);Set(r,"katePos",new Vector2Int(x,y));return r;}
    static KaitEnemy E(KaitRun r,int x,int y,int hp=5,KaitEnemyType type=KaitEnemyType.Grunt)
    {var e=new KaitEnemy{id=100+r.enemies.Count,pos=new Vector2Int(x,y),hp=hp,maxHp=hp,type=type,life=KaitEnemyLife.Active};r.enemies.Add(e);return e;}
    static void S(KaitRun r,params KaitSkill[] skills){foreach(var s in skills){r.skills.Add(s);Assert.IsTrue(r.TryUseSkill(s,-1,out _));}}
    static void Exhaust(KaitRun r,int ki=0){r.Yummn.phase=YummnPhase.Exhausted;r.Yummn.ki=ki;}
    static void Aim(KaitEnemy e,Vector2Int p){e.intent=new KaitIntent{type=KaitIntentType.Melee,origin=e.pos,target=p,damage=1};e.intent.affectedCells.Add(p);}
    static KaitTurnResult Context(KaitRun r)=>new KaitTurnResult{yummnAction=new YummnActionContext{phaseAtStart=r.KiPhase,startCell=r.katePos}};
    static void Rift(KaitRun r,int x,int y,int tier=1)=>r.spawns.Add(new KaitSpawnRequest{targetCell=new Vector2Int(x,y),sourceThreatCell=new Vector2Int(x-1,y-1),tier=tier});
    static void Locked(KaitRun r){for(int x=0;x<5;x++)for(int y=0;y<5;y++)if(!r.threatPillars[x,y])r.threat[x,y]=(x+y)%2==0?2:4;}
    [Test] public void T01_BurstMovementNoSupplyNoPhase(){var r=R();r.threat[1,2]=2;var a=r.TryGlobalInput(KaitDirection.Right);Assert.IsTrue(a.valid&&a.threatChanged);Assert.AreEqual(0,a.newThreatCells.Count);Assert.AreEqual(0,r.EnemyResolveCount);}
    [Test] public void T02_StationaryNonlethalStillMerges(){var r=R();E(r,2,3);r.threat[1,2]=r.threat[2,2]=2;var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,a.merges.Count);Assert.AreEqual(0,a.newThreatCells.Count);Assert.IsTrue(a.yummnAction.stationaryPunch);}
    [Test] public void T03_DefaultKillFollowOneSupplyOnePhase(){var r=R();E(r,2,3,1);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,a.newThreatCells.Count);Assert.AreEqual(1,r.EnemyResolveCount);Assert.AreEqual(new Vector2Int(2,3),r.katePos);Assert.AreEqual(0,a.yummnAction.preHitTravelCells);}
    [Test] public void T04_SecondaryKillsBatchOnce(){var r=R();E(r,2,3,1);E(r,3,3,1);r.passives.Add(KaitPassive.FireSnake);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,a.yummnAction.requestedTwos);Assert.AreEqual(2,a.newThreatCells.Count);Assert.AreEqual(2,r.kills);Assert.AreEqual(2,a.yummnAction.killIds.Distinct().Count());Assert.AreEqual(1,r.EnemyResolveCount);}
    [Test] public void T05_AlternativeKillFollowNoSupply(){var r=R(true);E(r,2,3,1);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(new Vector2Int(2,3),r.katePos);Assert.AreEqual(0,a.newThreatCells.Count);Assert.AreEqual(1,r.EnemyResolveCount);}
    [Test] public void T06_AlternativeSlidePunchSuppliesOnce(){var r=R(true);E(r,4,3,1);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,a.yummnAction.preHitTravelCells);Assert.AreEqual(1,a.newThreatCells.Count);Assert.AreEqual(1,r.EnemyResolveCount);}
    [Test] public void T07_AlternativeExhaustedStep(){var r=R(true);Exhaust(r);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,a.newThreatCells.Count);Assert.AreEqual(1,r.EnemyResolveCount);Assert.AreEqual(1,r.Ki);}
    [Test] public void T08_OverrideKillsTwoSupplyOne(){var r=R(true);E(r,2,3,1);E(r,3,3,1);S(r,KaitSkill.FrostBreath);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,r.kills);Assert.AreEqual(1,a.newThreatCells.Count);Assert.IsFalse(a.yummnAction.isPunchAction);}
    [Test] public void T09_PalmFollowDoesNotChangePrehitTravel(){var r=R(true);E(r,2,3);S(r,KaitSkill.Palm);r.passives.Add(KaitPassive.FollowThrough);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(new Vector2Int(2,3),r.katePos);Assert.AreEqual(0,a.yummnAction.preHitTravelCells);Assert.AreEqual(0,a.newThreatCells.Count);}
    [Test] public void T10_ThresholdMapsAnd32Reward(){foreach(bool eight in new[]{false,true})foreach(int value in new[]{4,8,16,32,64,128}){var r=R(false,eight);r.threat[1,2]=r.threat[2,2]=value/2;var a=r.TryGlobalInput(KaitDirection.Right);if(eight&&value==4)Assert.AreEqual(0,r.spawns.Count);else Assert.AreEqual(Mathf.Clamp((int)Mathf.Log(value,2)-(eight?2:1),1,5),r.spawns.Single().tier);Assert.AreEqual(value==32?1:0,r.rewardQueue.Count);}}
    [Test] public void T11_SnapshotReplayAndLegacy(){var r=new KaitRun();r.SelectCharacter(KaitCharacter.Yummn,81,new YummnRulesSnapshot(YummnTileSupplyMode.SkipStationaryPunch,true));r.TryGlobalInput(KaitDirection.Right);var save=r.SaveReplay();r.SelectCharacter(KaitCharacter.Yummn,81,new YummnRulesSnapshot());Assert.IsTrue(r.RestoreReplay(save));Assert.IsTrue(r.Yummn.rules.SpawnFromEight);Assert.AreEqual(YummnTileSupplyMode.SkipStationaryPunch,r.Yummn.rules.Supply);Assert.AreEqual(save,r.SaveReplay());r.SelectCharacter(KaitCharacter.Yummn,81,YummnRulesSnapshot.OldV08());r.TryGlobalInput(KaitDirection.Right);var old=JsonUtility.FromJson<KaitRun.ReplaySave>(r.SaveReplay());old.yummnRules=null;Assert.IsTrue(r.RestoreReplay(JsonUtility.ToJson(old)));Assert.IsTrue(r.Yummn.rules.Legacy);Assert.AreEqual(1,r.NormalTileSpawnCount);Assert.AreEqual(4,new[]{new YummnRulesSnapshot(),new YummnRulesSnapshot(YummnTileSupplyMode.KillOnly,true),new YummnRulesSnapshot(YummnTileSupplyMode.SkipStationaryPunch),new YummnRulesSnapshot(YummnTileSupplyMode.SkipStationaryPunch,true)}.Select(s=>s.ScoreKey).Distinct().Count());}
    [Test] public void T12_DeathDuplicateNoRewards(){var r=R();var e=E(r,2,3,1);var a=Context(r);Call(r,"YummnHit",e,1,Vector2Int.right,YummnDamageCause.Punch,a);Call(r,"YummnHit",e,1,Vector2Int.right,YummnDamageCause.Counter,a);Assert.AreEqual(1,r.kills);Assert.AreEqual(1,a.yummnAction.killIds.Count);}
    [Test] public void T13_LastKiKillBeforePhase(){var r=R();r.Yummn.ki=1;r.passives.Add(KaitPassive.PerfectSelf);E(r,2,3,1);r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,r.Ki);Assert.AreEqual(YummnPhase.Burst,r.KiPhase);Assert.AreEqual(0,r.Yummn.metrics.perfectKi);Assert.AreEqual(1,r.EnemyResolveCount);}
    [Test] public void T14_ExhaustAndKillOrNotSum(){var r=R();Exhaust(r);E(r,2,3,1);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,r.EnemyResolveCount);Assert.AreEqual(1,r.Yummn.metrics.recoveryKi);Assert.AreEqual(YummnEnemyPhaseReason.Kill|YummnEnemyPhaseReason.Exhaustion,a.yummnAction.enemyPhaseReason);}
    [Test] public void T15_BurstKillNoRecovery(){var r=R();r.Yummn.ki=1;E(r,2,3,1);r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,r.Ki);Assert.AreEqual(0,r.Yummn.metrics.recoveryKi);}
    [Test] public void T16_FlurryFireCompleteBeforeEnemyActs(){var r=R();E(r,2,3,2);E(r,3,3,1);var e=E(r,2,4);Aim(e,new Vector2Int(2,3));S(r,KaitSkill.Flurry);r.passives.Add(KaitPassive.FireSnake);var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(2,a.yummnPunches);Assert.AreEqual(2,r.kills);Assert.Less(a.yummnEvents.FindLastIndex(v=>v.kind==YummnEventKind.Kill),a.yummnEvents.FindIndex(v=>v.kind==YummnEventKind.EnemyAttack));Assert.AreEqual(2,a.newThreatCells.Count);}
    [Test] public void T17_CounterKillIncludedInBatch(){var r=R(false,false,3,3);Exhaust(r);E(r,1,3,1,KaitEnemyType.Swordsman);r.passives.Add(KaitPassive.Opportunist);S(r,KaitSkill.ShapeIce);r.Yummn.ki=1;var a=r.TryGlobalInput(KaitDirection.Up);Assert.AreEqual(1,r.kills);Assert.AreEqual(1,a.newThreatCells.Count);Assert.AreEqual(1,r.EnemyResolveCount);Assert.AreEqual(1,r.Yummn.metrics.spawnChecks);}
    [Test] public void T18_BornAfterPhaseNoFreeAction(){var r=R();Exhaust(r);Rift(r,3,3,2);var a=r.TryGlobalInput(KaitDirection.Right);var e=r.EnemyAt(new Vector2Int(3,3));Assert.NotNull(e);Assert.AreEqual(KaitIntentType.None,e.intent.type);Assert.IsFalse(a.enemyActions.Any(x=>x.enemyId==e.id));}
    [Test] public void T19_FollowOccupiesRift(){var r=R();E(r,2,3,1);Rift(r,2,3);r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,r.spawns.Count);Assert.IsNull(r.EnemyAt(r.katePos));}
    [Test] public void T20_SwordsmanMoveAimAttackSeparated(){var r=R(false,false,3,3);var e=E(r,1,3,3,KaitEnemyType.Swordsman);Call(r,"ResolveYummnEnemyPhase",Context(r));Assert.AreEqual(new Vector2Int(2,3),e.pos);Assert.AreEqual(KaitIntentType.None,e.intent.type);Call(r,"ResolveYummnEnemyPhase",Context(r));Assert.AreEqual(KaitIntentType.Melee,e.intent.type);Assert.AreEqual(3,r.kateHp);Call(r,"ResolveYummnEnemyPhase",Context(r));Assert.AreEqual(2,r.kateHp);}
    [Test] public void T21_BurstKillConsumesControlAndDarkness(){var r=R();E(r,2,3,1);var e=E(r,2,4);e.yummnFrozen=true;Aim(e,new Vector2Int(2,3));r.Yummn.darkness=new Vector2Int(4,4);r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(3,r.kateHp);Assert.IsFalse(e.yummnFrozen);Assert.AreEqual(KaitIntentType.None,e.intent.type);Assert.AreEqual(YummnRun.NoCell,r.Yummn.darkness);}
    [Test] public void T22_PatientConsumedOnBurstKill(){var r=R();E(r,2,3,1);Aim(E(r,2,4),new Vector2Int(2,3));S(r,KaitSkill.PatientDefense);r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(3,r.kateHp);Assert.IsFalse(r.Yummn.defense);}
    [Test] public void T23_CounterFullDoesNotStopRemainingActors(){var r=R(false,false,3,3);Exhaust(r,1);r.passives.Add(KaitPassive.Opportunist);E(r,1,3,1,KaitEnemyType.Swordsman);Aim(E(r,3,4),r.katePos);Call(r,"ResolveYummnEnemyPhase",Context(r));Assert.AreEqual(3,r.Ki);Assert.AreEqual(2,r.kateHp);Assert.AreEqual(YummnPhase.Exhausted,r.KiPhase);}
    [Test] public void T24_RiftDedupAndBossWait(){var r=R();var a=Context(r);foreach(int v in new[]{4,32,8})Call(r,"QueueYummnRift",new KaitMergeEvent{resultValue=v,threatCell=new Vector2Int(2,2)},a);Assert.AreEqual(1,r.spawns.Count);Assert.AreEqual(4,r.spawns[0].tier);Set(r,"bossPending",true);Set(r,"bossPendingCell",r.katePos);Call(r,"SpawnShieldKnight",a);Assert.IsFalse(r.bossSpawned);Set(r,"katePos",new Vector2Int(2,2));Call(r,"SpawnShieldKnight",a);Assert.IsTrue(r.bossSpawned);}
    [Test] public void T25_LockedLosesWithoutReset(){var r=R();Locked(r);var before=(int[,])r.threat.Clone();r.TryGlobalInput(KaitDirection.Right);Assert.IsTrue(r.ended);Assert.AreEqual("ThreatBoardLocked",r.endReason);CollectionAssert.AreEqual(before,r.threat);}
    [Test] public void T26_FullMergeAvailableContinues(){var r=R();Locked(r);r.threat[2,2]=r.threat[3,2];Assert.IsFalse(r.IsYummnThreatLocked());r.TryGlobalInput(KaitDirection.Right);Assert.IsFalse(r.ended);}
    [Test] public void T27_OneBlockedDirectionNotLock(){var r=R();r.threat[4,2]=2;Assert.IsFalse((bool)Call(r,"YummnThreatCanChange",KaitDirection.Right));Assert.IsFalse(r.IsYummnThreatLocked());var saved=r.SaveReplay();for(int i=0;i<10;i++)r.IsYummnThreatLocked();Assert.AreEqual(saved,r.SaveReplay());}
    [Test] public void T28_PasswallEffectiveSegment(){var r=R();Array.Clear(r.threatPillars,0,r.threatPillars.Length);r.threatPillars[2,2]=true;for(int x=0;x<5;x++)for(int y=0;y<5;y++)if(!r.threatPillars[x,y])r.threat[x,y]=1<<(x+5*y+1);r.threat[1,2]=r.threat[3,2]=8;Assert.IsTrue(r.IsYummnThreatLocked());var walls=(bool[,])r.walls.Clone();r.passives.Add(KaitPassive.Passwall);Assert.IsFalse(r.IsYummnThreatLocked());var a=r.TryGlobalInput(KaitDirection.Right);Assert.IsTrue(a.merges.Any(m=>m.resultValue==16));CollectionAssert.AreEqual(walls,r.walls);}
    [Test] public void T29_ArchiveBeforeLockCheckAndBagNoDouble(){var r=R();Locked(r);r.passives.Add(KaitPassive.OldNewsArchive);var a=r.TryGlobalInput(KaitDirection.Right);Assert.IsFalse(r.ended);Assert.AreEqual(1,a.merges.Count(m=>m.systemMerge));Assert.AreEqual(1,r.PassiveTriggerCount(KaitPassive.OldNewsArchive));r=R();r.passives.AddRange(new[]{KaitPassive.OldNewsArchive,KaitPassive.BagHolding});Locked(r);a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(1,r.PassiveTriggerCount(KaitPassive.BagHolding));Assert.IsFalse(r.ended);}
    [Test] public void T30_FullSupplyDropsNoDebtNoFalseLoss(){var r=R();Locked(r);r.threat[2,2]=r.threat[2,3];var a=Context(r);a.yummnAction.killIds.Add(100);Call(r,"SupplyYummnTwos",a);Assert.AreEqual(1,a.yummnAction.droppedTwos);Assert.IsFalse(r.IsYummnThreatLocked());r.threat[1,1]=0;var b=Context(r);Call(r,"SupplyYummnTwos",b);Assert.AreEqual(0,b.yummnAction.requestedTwos);Assert.AreEqual(0,r.threat[1,1]);}
    [Test] public void T31_BossVictoryBeforeSupplyOrLockedLoss(){var r=R();Locked(r);var b=E(r,2,3,1,KaitEnemyType.ShieldKnight);b.facing=Vector2Int.right;Set(r,"bossEnemyId",b.id);var a=r.TryGlobalInput(KaitDirection.Right);Assert.IsTrue(r.won);Assert.AreEqual(0,r.EnemyResolveCount);Assert.AreEqual(0,a.newThreatCells.Count);}
    [Test] public void T32_LockedWithBossAliveLoses(){var r=R();Locked(r);E(r,4,4,8,KaitEnemyType.ShieldKnight);r.TryGlobalInput(KaitDirection.Right);Assert.IsFalse(r.won);Assert.AreEqual("ThreatBoardLocked",r.endReason);}
    [Test] public void T33_DeathStopsActorsRecoveryAndHealing(){var r=R();Set(r,"kateHp",1);Exhaust(r,2);r.passives.Add(KaitPassive.Wholeness);E(r,2,3,1);Aim(E(r,2,4),new Vector2Int(2,3));Aim(E(r,3,3),new Vector2Int(2,3));var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual("PlayerDead",r.endReason);Assert.AreEqual(1,a.enemyActions.Count);Assert.AreEqual(0,r.Yummn.metrics.heals);Assert.AreEqual(0,a.newThreatCells.Count);}
    [Test] public void T34_TerminalRewardSettingsCannotRescue(){var r=R();Locked(r);r.TryGlobalInput(KaitDirection.Right);var pack=new KaitRewardPack();pack.choices.Add(YummnCatalog.Get("M05"));r.rewardQueue.Enqueue(pack);Assert.IsFalse(r.SelectReward(0));r.config.playerInvincible=true;r.RecordSettingsChange();Assert.IsFalse(r.TryGlobalInput(KaitDirection.Left).valid);Assert.AreEqual("ThreatBoardLocked",r.endReason);}
    public static List<int> IdealInventory(int initial,bool eight){var v=Enumerable.Repeat(2,initial).ToList();for(int i=0;i<256;i++){int pair=v.GroupBy(x=>x).Where(g=>g.Count()>1).Select(g=>g.Key).DefaultIfEmpty(0).Min();if(pair==0||pair>=128)break;v.Remove(pair);v.Remove(pair);v.Add(pair*2);if(pair*2>=(eight?8:4))v.Add(2);}return v.OrderByDescending(x=>x).ToList();}
    [Test] public void T35_DefaultIdealThreeStarvesNotLocked(){CollectionAssert.AreEqual(new[]{8,4,2},IdealInventory(3,false));var r=R();r.threat[1,1]=8;r.threat[2,1]=4;r.threat[3,1]=2;Assert.IsTrue(r.YummnSupplyStarved);Assert.IsFalse(r.IsYummnThreatLocked());Assert.IsFalse(r.ended);}
    [Test] public void T36_EightStartThreeOrFourCannotReachBoss(){CollectionAssert.AreEqual(new[]{4,2},IdealInventory(3,true));CollectionAssert.AreEqual(new[]{8,2},IdealInventory(4,true));Assert.Greater(128-62,23);}
    [Test] public void T37_TraceAndBagNeverSecretlySupply(){var r=R(true);r.passives.Add(KaitPassive.PassWithoutTrace);Assert.AreEqual(0,r.TryGlobalInput(KaitDirection.Right).newThreatCells.Count);r=R();Assert.IsFalse(r.EligibleAbilities().Any(d=>d.passive==KaitPassive.PassWithoutTrace));r.passives.Add(KaitPassive.BagHolding);r.threat[1,2]=r.threat[2,2]=r.threat[3,2]=2;var a=r.TryGlobalInput(KaitDirection.Right);Assert.AreEqual(0,a.newThreatCells.Count);Assert.AreEqual(1,r.PassiveTriggerCount(KaitPassive.BagHolding));}
    [Test] public void T38_KaitSameSeedUnaffectedByYummnPresets(){var a=new KaitRun();var b=new KaitRun();a.SelectCharacter(KaitCharacter.Kait,3801);b.SelectCharacter(KaitCharacter.Kait,3801,new YummnRulesSnapshot(YummnTileSupplyMode.SkipStationaryPunch,true));for(int i=0;i<80&&!a.ended;i++){var d=(KaitDirection)(i%4);if(a.chainActive){a.ContinueChain(d);b.ContinueChain(d);}else{a.TryGlobalInput(d);b.TryGlobalInput(d);}CollectionAssert.AreEqual(a.threat,b.threat);Assert.AreEqual(a.kateHp,b.kateHp);Assert.AreEqual(a.kills,b.kills);Assert.AreEqual(a.SaveReplay(),b.SaveReplay());}}
}
