from pathlib import Path
P=Path('Assets/Scripts')
def edit(f,a,b):
 p=P/f;s=p.read_text(encoding='utf-8-sig');assert a in s,(f,a);p.write_text(s.replace(a,b),encoding='utf-8')
edit('KaitSpineView.cs','skeletonGraphic.Skeleton.Data.FindAnimation(Idle)!=null?Idle:"01_idle"','skeletonGraphic.Skeleton.Data.FindAnimation("idle")!=null?"idle":skeletonGraphic.Skeleton.Data.FindAnimation(Idle)!=null?Idle:"01_idle"')
edit('KaitSpineView.cs','        if (graphic.Skeleton.Data.FindAnimation("108201_skill0") != null)\n        {','        if(graphic.Skeleton.Data.FindAnimation("uniqueskill")!=null)\n        {\n            if(graphic.Skeleton.Data.FindAnimation(name)!=null)return name;\n            if(name==Run)return "run";if(name==Victory)return "win";if(name==Die)return "die";if(name==Damage)return "hit_1";\n            if(name==Attack||name==ChainAttack)return "attack";if(name==Stop)return "land";\n            if(name==OtherSkill)return "skill";return "idle";\n        }\n        if (graphic.Skeleton.Data.FindAnimation("108201_skill0") != null)\n        {')
# Only source pack has plain idle: select its optional named skin before measuring bounds.
edit('KaitSpineView.cs','        skeletonGraphic.AnimationState.SetAnimation(0,','        if(skeletonGraphic.Skeleton.Data.FindSkin("3")!=null){skeletonGraphic.Skeleton.SetSkin("3");skeletonGraphic.Skeleton.SetSlotsToSetupPose();}\n        skeletonGraphic.AnimationState.SetAnimation(0,')
edit('EnemySpineView.cs','string.IsNullOrEmpty(animationPrefix)','animationPrefix==null')
edit('EnemySpineView.cs','prefix + LandingSuffix','Resolve(prefix + LandingSuffix)')
edit('EnemySpineView.cs','prefix + DamageSuffix','Resolve(prefix + DamageSuffix)')
# Leave public constant intact for legacy tests; resolve prepare per skeleton.
edit('EnemySpineView.cs','==PrepareAttackAnimation','==Resolve(PrepareAttackAnimation)')
edit('EnemySpineView.cs','SetAnimation(0,PrepareAttackAnimation,true)','SetAnimation(0,Resolve(PrepareAttackAnimation),true)')
edit('EnemySpineView.cs','Duration(PrepareAttackAnimation)','Duration(Resolve(PrepareAttackAnimation))')
edit('EnemySpineView.cs','    private float Duration(string animation)','    private string Resolve(string animation)\n    {\n        if(graphic.Skeleton.Data.FindAnimation(animation)!=null)return animation;\n        string fallback=animation==LandingSuffix?"land":animation==DamageSuffix?"hit_1":animation==PrepareAttackAnimation?"prepare":"idle";\n        return graphic.Skeleton.Data.FindAnimation(fallback)!=null?fallback:"idle";\n    }\n    private float Duration(string animation)')
edit('KaitCharacterSelection.cs','SaveKeys(KaitCharacter c)=>','SaveKeys(KaitCharacter c)=>c==KaitCharacter.Reynard?new[]{KaitVersion.ReynardSaveKey}:')
edit('KaitGame.Yummn.cs','waitButton.gameObject.SetActive(run.IsYummn)','waitButton.gameObject.SetActive(run.IsYummn||run.IsReynard)')
edit('KaitGame.cs','run.IsYummn&&AutoInputReady','(run.IsYummn||run.IsReynard)&&AutoInputReady')
edit('KaitGame.cs','storybookCharacter.text=run.IsYummn?"Yummn":"Kait"','storybookCharacter.text=run.Character.ToString()')
edit('KaitGame.cs','if (!enemySkeletonData.TryGetValue(enemy.type, out SkeletonDataAsset data) || data == null) return null;','SkeletonDataAsset data=run.IsReynard?Resources.Load<SkeletonDataAsset>("Characters/Reynard/"+ReynardArt.EnemyId(enemy.type)+"/"+ReynardArt.EnemyId(enemy.type)+"_SkeletonData"):enemySkeletonData.TryGetValue(enemy.type,out var oldData)?oldData:null;\n        if(data==null)return null;')
edit('KaitGame.cs','EnemySpineView.Create(data, EnemyAnimationPrefix(enemy.type)','EnemySpineView.Create(data, run.IsReynard?"":EnemyAnimationPrefix(enemy.type)')
edit('KaitGame.cs','        if(run.IsYummn){yield return PlayYummnTurn','        if(run.IsReynard){yield return PlayReynardTurn(result,start,enemySnapshot,spawnSnapshot);yield break;}\n        if(run.IsYummn){yield return PlayYummnTurn')
edit('KaitCardSkin.cs','        string artName=def.id.Substring','        if(def.id.StartsWith("reynard.")){s=ReynardArt.Load("Cards/"+def.id.Substring(8));if(s!=null)cache[key]=s;return s;}\n        string artName=def.id.Substring')
edit('KaitCardLibrary.cs','new[]{KaitCharacter.Kait,KaitCharacter.Yummn}','new[]{KaitCharacter.Kait,KaitCharacter.Yummn,KaitCharacter.Reynard}')
edit('KaitCardLibrary.cs','c==KaitCharacter.Kait?294:188','294-(int)c*106')
edit('KaitCardLibrary.cs','c==KaitCharacter.Yummn?YummnCatalog.Cards:KaitAbilityCatalog.All','c==KaitCharacter.Reynard?ReynardCatalog.Cards:c==KaitCharacter.Yummn?YummnCatalog.Cards:KaitAbilityCatalog.All')
edit('KaitCardLibrary.cs','i<2?i==(int)Character:i-3==Rarity','i<3?i==(int)Character:i-4==Rarity')
edit('KaitCardLibrary.cs','string cost=def.experimental?','string cost=def.spellLevel>0?ReynardCatalog.Roman(def.spellLevel)+"环":def.experimental?')
